channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - psutil==7.0.0
  - scikit-learn==1.4.0
  - scipy==1.10.1
  - hyperopt==0.2.7
name: mlflow-env
